FROM python:3.11-bookworm

# Install discord.py
RUN python3 -m pip install -U discord.py

# Install pytz
RUN python3 -m pip install -U pytz

# Install pyinstaller
RUN python3 -m pip install -U pyinstaller